version: "3"
services:
  authentication:
    build: .
    ports:
      - "5000:5000"
    links:
      - auth-db
    environment:
      DB_URI: "postgresql://postgres:example@auth-db:5432/postgres"
  auth-db:
    image: "postgres"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    expose:
      - 5432
    ports: # only necessary for connecting manually
      - "5432:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
